version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=curso_nestjs
    volumes:
      - curso_nestjs_pg_data:/bitnami/postgresql

volumes:
  curso_nestjs_pg_data: